<a href="https://colab.research.google.com/github/pulkitmehtawork/Pytorch/blob/master/Neural_Network_Using_Pytorch_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook , we will develop a neural network from scratch using Pytorch .
Reference : AV free course - Intro to Pytorch

In [5]:
import torch 
import numpy as np 

In [6]:
# Input Tensor 

X = torch.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
# output tensor
y = torch.Tensor([[1],[1],[0]])

In [7]:
print(X,'\n')
print(y)

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.]]) 

tensor([[1.],
        [1.],
        [0.]])


In [8]:
#sigmoid function 
def sigmoid(x):
  return 1/(1+torch.exp(-x))

In [9]:
# derivative of sigmoid 
def derivatives_sigmoid(x):
  return sigmoid(x)* ( 1- sigmoid(x))

In [17]:
# initilaize parameters

epoch =10000
lr = 0.1 # learning rate
inputlayer_neurons = X.shape[1]  #number of features in input
hiddenlayer_neurons  =3
output_neurons = 1


In [11]:
  #weight and bias initialization
wh=torch.randn(inputlayer_neurons, hiddenlayer_neurons).type(torch.FloatTensor)
bh=torch.randn(1, hiddenlayer_neurons).type(torch.FloatTensor)
wout=torch.randn(hiddenlayer_neurons, output_neurons)
bout=torch.randn(1, output_neurons)

In [12]:
wh

tensor([[-0.9757, -0.0916, -1.2599],
        [-0.6971,  1.6515, -0.9225],
        [ 1.1155,  0.5425, -0.0460],
        [-0.3337,  0.6472,  0.9639]])

In [18]:
for i in range(epoch):
   #Forward Propogation
   hidden_layer_input1 = torch.mm(X, wh)
   hidden_layer_input = hidden_layer_input1 + bh
   hidden_layer_activations = sigmoid(hidden_layer_input)
   
   output_layer_input1 = torch.mm(hidden_layer_activations, wout)
   output_layer_input = output_layer_input1 + bout
   output = sigmoid(output_layer_input)
   #Backpropagation
   
   E = y-output
   slope_output_layer = derivatives_sigmoid(output)
   slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
   d_output = E * slope_output_layer
   Error_at_hidden_layer = torch.mm(d_output, wout.t())
   d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer

   wout += torch.mm(hidden_layer_activations.t(), d_output) *lr
   bout += d_output.sum() *lr
   wh += torch.mm(X.t(), d_hiddenlayer) *lr
   bh += d_output.sum() *lr



In [19]:
print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 tensor([[1.],
        [1.],
        [0.]]) 

predicted :
 tensor([[9.9988e-01],
        [9.9985e-01],
        [2.8330e-04]])
